name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  spec:
    runs-on: ubuntu-latest
    services:
    steps:
      - name: Run tests
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec --format=doc
